---
- hosts: nfs
  tasks:
      - lvol:
         vg: "/dev/vgcloud"
         lv: "vishat123-lv1"
         size: "1024"

      - filesystem:
         fstype: ext4
         dev: "/dev/vgcloud/vishat123-lv1"

      - file:
         path: "/object/vishat123-lv1"
         state: directory

      - mount:
         path: "/object/vishat123-lv1"
         src: "/dev/vgcloud/vishat123-lv1"
         fstype: ext4
         state: mounted

      - lineinfile:
         path: /etc/exports
         state: present
         insertafter: EOF
         line: '/object/vishat123-lv1 192.168.43.132(rw,no_root_squash)
'
  
      - service:
         name: nfs
         state: restarted

- hosts: vishat123
  tasks:
      - file:
         path: "/media/vishat123"
         state: directory

      - mount:
         path: "/media/vishat123"
         src: "192.168.43.238:/object/vishat123-lv1"
         fstype: nfs
         state: mounted
